### ISSUE TITLE
receiver to foldState

### ISSUE THREAD

**Issue by cryogenian** [cryogenian/slamdata#23]
asyncronous messages like ajax can't be just folded. other option to define global event listener for xhr requests. And use it for all global services

**Comment by jdegoes** [comment]
Now what if we start out with `Channel AjaxRequest`. Then we map that into `Signal (ajax :: AJAX) AjaxResponse)`. Then the response can be folded over and mapped into the view.

That would work, wouldn't it?

**Comment by cryogenian** [comment]
Then xhr-component will go to folder function, that in <code>Component</code> or to field in state of component that uses it.

**Comment by jdegoes** [comment]
That is fine, the `Signal` of response (with effect) could be folded into the state. Right?

**Comment by cryogenian** [comment]
Yes, it can.

**Comment by cryogenian** [comment]
But state can be inconsistent in callback. This is very similar with <code>view :: Recevier _ _ -> State -> Eff _ VTree</code> because it produces effects from state and sends messages that asynchronously update state. 
Maybe the problem not in <code>foldState</code> but in <code>view</code>

**Comment by jdegoes** [comment]
Instead of updating the state, you can produce a function which updates the state. This plays better with asynchronous code. We had (/have) lots of strange bugs related to this in the nodewebkit version, with asynchronous actions causing reversion of parts of the state which updated since the initial request.

**Comment by cryogenian** [comment]
This is nice idea. 

I think it can be also done something like 

``` purescript
data ComponentMessage input = System SystemMessages | Input input
type Receiver action eff = Eff eff (Channel action)

view :: ComponentMessage -> Receiver ComponentMessage _ -> State -> Eff _ Unit 
view message send = do
  case message of 
    System ToRender -> do 
      let vdom = div {"onclick": send (Input Clicked)} []
      send (System vdom) 
    Input Clicked -> do
      xhr <- XHR.construct
      xhr (send <<< Input <<< AjaxGetted) {
        -- ajax config
        }

```

<code>Component</code> can just listen <code>channel</code> on <code>System (Render vdom)</code> to render, and <code>foldState</code> can listen <code>Input any</code> to foldState. 
Both cases could be encapsulated in <code>Component</code> module

**Comment by cryogenian** [comment]
- https://gist.github.com/cryogenian/6b9019feb573330bbb9e
- Stick
  - abandon `xhr-signal` to simple callbacks.
  - put all effectful communication to `view`
  - provide function that is called only one time after constructing component

**Comment by cryogenian** [comment]
I've putted effectful computations to `view`
